// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsNCcVqj6vuD_WR4tncdIlI8wZc1SogbA',
    appId: '1:815632878913:web:7f1cebf467d44fe5dc25c0',
    messagingSenderId: '815632878913',
    projectId: 'sitetititas',
    authDomain: 'sitetititas.firebaseapp.com',
    databaseURL: 'https://sitetititas-default-rtdb.firebaseio.com',
    storageBucket: 'sitetititas.appspot.com',
    measurementId: 'G-QVS8D0P7C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAM1eYg8uwfQhmH2wIWJBhOGVOKvyFN-o',
    appId: '1:815632878913:android:360a3f2975ed8163dc25c0',
    messagingSenderId: '815632878913',
    projectId: 'sitetititas',
    databaseURL: 'https://sitetititas-default-rtdb.firebaseio.com',
    storageBucket: 'sitetititas.appspot.com',
  );
}
